export const site = {
  name: 'Start UC3M',
  claim: 'Piensa diferente, actúa con propósito',
  description:
    'Start UC3M es la asociación de emprendedores de la Universidad Carlos III de Madrid: eventos, comunidad y proyectos para pasar de la idea a algo real.',
  email: 'info@startuc3m.org',
  course: '2026/27',
  social: {
    instagram: 'https://www.instagram.com/startuc3m/',
    linkedin: 'https://www.linkedin.com/company/start-uc3m/',
    tiktok: 'https://www.tiktok.com/@startuc3m',
    youtube: 'https://www.youtube.com/@StartUC3MG',
  },
  nav: [
    { label: 'Eventos', href: '/eventos' },
    { label: 'Podcast', href: '/podcast' },
    { label: 'Equipo', href: '/equipo' },
    { label: 'Blog', href: '/blog' },
    { label: 'Patrocina', href: '/patrocina' },
    { label: 'Recursos', href: '/recursos' },
  ],
  // logo: ruta en public/logos (los que faltan van en texto hasta que Partnerships pase el SVG)
  sponsors: [
    { name: 'NomuLabs', logo: '/logos/nomulabs.png', tier: 'Partner' },
    { name: 'Pitchless', logo: '/logos/pitchless.jpg', tier: 'Partner' },
    { name: 'Lovable', logo: '/logos/lovable.png', tier: 'Evento' },
    { name: 'Racks', tier: 'Evento' },
    { name: 'TeamLabs', logo: '/logos/teamlabs.png', tier: 'Colaborador' },
    { name: 'Madrid Startup Bar', tier: 'Colaborador' },
    { name: 'Opinión20', logo: '/logos/opinion20.png', tier: 'Colaborador' },
    { name: 'ULVMAND', logo: '/logos/ulvmand.png', tier: 'Colaborador' },
  ],
  departments: [
    { name: 'Junta directiva', short: 'Marca el rumbo', desc: 'Marca el rumbo de Start UC3M. Define los objetivos del curso, coordina el trabajo de todos los departamentos y representa a la asociación ante la universidad y el resto del ecosistema emprendedor.' },
    { name: 'Eventos', short: 'Da forma a todo lo que organizamos', desc: 'Da forma a todo lo que la asociación organiza. Diseña el calendario del curso, coordina los espacios, los ponentes y los materiales de cada convocatoria, y se ocupa de que el día del evento todo salga según lo previsto.' },
    { name: 'Comunicación', short: 'Da voz a Start', desc: 'Da voz a Start UC3M. Gestiona las redes sociales, escribe los contenidos que se publican y cubre los eventos con fotografía y vídeo para que quede constancia de lo que se hace.' },
    { name: 'Marketing', short: 'Cómo se ve Start desde fuera', desc: 'Se encarga de cómo se ve Start UC3M desde fuera. Diseña las campañas de cada evento, cuida la identidad visual de la asociación y crea los materiales gráficos que acompañan a todo lo que se publica.' },
    { name: 'RRHH', short: 'Las personas que forman Start', desc: 'Se encarga de las personas que forman Start. Elige a quién entra, acompaña a los nuevos durante sus primeros meses y organiza las formaciones del curso y las actividades internas que mantienen unido al equipo.' },
    { name: 'Partnerships', short: 'Las empresas que apoyan a Start', desc: 'Construye la relación con las empresas que apoyan a Start UC3M. Busca nuevos patrocinadores, negocia las condiciones de cada colaboración y mantiene el contacto con los socios a lo largo del curso.' },
    { name: 'Legal', short: 'El marco jurídico', desc: 'Se ocupa del marco jurídico de la asociación. Revisa los convenios con empresas y patrocinadores, mantiene al día los estatutos y se asegura de que cada actividad cumple con la normativa de la universidad.' },
    { name: 'DTE', short: 'Desarrollo, tecnología y experiencia', desc: '[COPY] Diseña y construye los productos digitales de Start: la web, las herramientas internas y la experiencia de los eventos.' },
    { name: 'IT', short: 'Producto y web', desc: 'Construye y mantiene la web, las herramientas internas y todo lo que Start necesita para funcionar en digital.' },
  ],
  team: [
    { name: 'Ioana Nedelcu', photo: '/media/equipo/ioana_nedelcu.jpeg', role: 'Presidenta', dept: 'Junta directiva', linkedin: 'https://www.linkedin.com/in/ioananedelcu/' },
    { name: 'Ana Giménez', photo: '/media/equipo/ana_gimenez.jpg', role: 'Vicepresidenta', dept: 'Junta directiva', linkedin: 'http://www.linkedin.com/in/ana-gimenez-de-luis-93a528293' },
    { name: 'Alejandro Ausina', photo: '/media/equipo/alejandro_ausina.jpg', role: 'Responsable', dept: 'IT', linkedin: 'https://www.linkedin.com/in/alejandro-ausina/' },
    { name: 'Lidia Wang', photo: '/media/equipo/lidia_wang.jpg', role: 'Responsable', dept: 'Marketing', linkedin: 'http://www.linkedin.com/in/lidia-wang-058433389' },
    { name: 'Irene Ibáñez', photo: '/media/equipo/irene_ibanez.jpeg', role: 'Responsable', dept: 'RRHH', linkedin: 'https://www.linkedin.com/in/ireneibanezcasao/' },
    { name: 'Alicia Gascón', photo: '/media/equipo/alicia_gascon.jpg', role: 'Responsable', dept: 'Eventos', linkedin: 'https://www.linkedin.com/in/alicia-gasc%C3%B3n-valero-41a828387/' },
    { name: 'Juan Vicente Zerpa', photo: '/media/equipo/juan_vicente.jpg', role: 'Asociado', dept: 'IT', linkedin: 'https://www.linkedin.com/in/juan-vicente-zerpa/' },
    { name: 'Uxío López', photo: '/media/equipo/uxio_lopez.png', role: 'Responsable', dept: 'Comunicación', linkedin: 'https://www.linkedin.com/in/uxio-lopez-0b6a09386/' },
    { name: 'María Martín', photo: '/media/equipo/maria_martin.jpg', role: 'Responsable', dept: 'Legal', linkedin: 'https://www.linkedin.com/in/maria-martin-dominguez-9569332a6/' },
    { name: 'Pedro Rodríguez', photo: '/media/equipo/pedro_rodriguez.jpg', role: 'Responsable', dept: 'Partnerships', linkedin: 'https://www.linkedin.com/in/pedro-rodr%C3%ADguez-ramos-2bb75a292/' },
    { name: 'María Aguilar', photo: '', role: 'Asociada', dept: 'RRHH', linkedin: '' },
    { name: 'Gonzalo Torrijos', photo: '/media/equipo/gonzalo_torrijos.jpeg', role: 'Asociado', dept: 'Eventos', linkedin: 'https://www.linkedin.com/in/gonzalo-torrijos/' },
    { name: 'Ángel Martín', photo: '', role: 'Futuro miembro', dept: 'DTE', linkedin: 'https://www.linkedin.com/in/aaangelmartin/' },
    { name: 'Marco Barroso', photo: '', role: 'Futuro miembro', dept: 'DTE', linkedin: 'https://www.linkedin.com/in/marcoobarroso/' },
    { name: 'Álvaro Carpintero', photo: '', role: 'Futuro miembro', dept: 'DTE', linkedin: 'https://www.linkedin.com/in/alvaarocl/' },
    { name: 'Pablo Juan', photo: '/media/equipo/pablo_juan.jpg', role: 'Asociado', dept: 'Legal', linkedin: 'https://www.linkedin.com/in/pablo-juan-conde/' },
  ],
  // { name, role: cargo + años (ej. "Presidenta 2022-23"), linkedin? } — pendiente de contenido real de RRHH
  alumni: [] as { name: string; role: string; linkedin?: string }[],
  tiers: [
    { name: 'Partner', tag: 'Fijo · todo el curso', desc: 'Tu marca dentro de Start de forma permanente: todos los eventos, la web, las redes y el campus.', perks: ['Logo en todos los eventos del curso', 'Presencia fija en web, links y newsletter', 'Acceso a la comunidad y a la bolsa de talento', 'Mesa propia en StartXperience y Start Camp', 'Episodio del podcast con tu equipo'] },
    { name: 'Patrocinio de evento', tag: 'Por evento', desc: 'Un evento concreto con tu naming, tu producto y tu gente dentro.', perks: ['Naming ("Buildathon × Tu marca")', 'Logo en cartelería, ficha y redes del evento', 'Charla, taller o reto propio', 'Perfiles de los asistentes que lo autoricen'] },
    { name: 'Colaborador', tag: 'En especie', desc: 'Producto, espacio, créditos o mentores.', perks: ['Logo en la ficha del evento', 'Agradecimiento en redes'] },
  ],
  // [COPY] hitos para "Quiénes somos" — Álvaro revisa textos; Ángel fija el diseño
  milestones: [
    { year: '2013', title: 'Nace Start', desc: 'Seis alumnos de ADE crean la asociación para conectar talento técnico, de diseño y de negocio.' },
    { year: '2015', title: 'Alternativa Emprender', desc: '[COPY] Tres ediciones del evento de referencia con ponencias y talleres.' },
    { year: '2019', title: 'Hack On Business', desc: '[COPY] Hackathon que junta a business con ingenieros en equipos multidisciplinares.' },
    { year: '2024', title: 'StartXperience', desc: '[COPY] Un día con startups pre-seed, inversores e incubadoras del ecosistema madrileño.' },
    { year: '2026', title: 'Buildathon y podcast', desc: '[COPY] Arrancamos el curso construyendo y lanzamos Start_Talks.' },
  ],
  pillars: [
    { title: 'Eventos', desc: '[COPY] Buildathon, hackathones, StartXperience, Start Camp: formatos para construir, no para escuchar.' },
    { title: 'Comunidad', desc: '[COPY] Más de 3.000 estudiantes, alumni que fundan e invierten, y empresas que apoyan.' },
    { title: 'Proyectos', desc: '[COPY] Acompañamos a los equipos que quieren sacar su proyecto adelante desde la universidad.' },
  ],
  links: [
    { label: 'Apuntarme al Buildathon', href: '/eventos/buildathon-pitchless-nomulabs', featured: true },
    { label: 'Quiero entrar en Start', href: '/unete' },
    { label: 'Podcast', href: '/podcast' },
    { label: 'Próximos eventos', href: '/eventos' },
    { label: 'Patrocina Start', href: '/patrocina' },
    { label: 'Blog', href: '/blog' },
  ],
  resources: [
    { cat: 'UC3M', title: 'Vicerrectorado de Emprendimiento UC3M', desc: 'Programas, incubadora y ayudas de la universidad.', url: 'https://www.uc3m.es/emprendimiento/emprende' },
    { cat: 'UC3M', title: 'Asociaciones de estudiantes', desc: 'Cómo funcionan las asociaciones y cómo crear la tuya.', url: 'https://www.uc3m.es/ss/Satellite/AsociacionesEst/es/TextoDosColumnas/1371383720362/' },
    { cat: 'Herramientas', title: 'Lovable', desc: 'Construye un MVP sin código. Lo usamos en el Buildathon.', url: 'https://lovable.dev' },
    { cat: 'Herramientas', title: 'Luma', desc: 'Para publicar y gestionar eventos.', url: 'https://luma.com' },
    { cat: 'Ecosistema', title: 'TeamLabs', desc: 'Laboratorio de aprendizaje radical y espacio de eventos en Madrid.', url: 'https://teamlabs.es' },
    { cat: 'Ecosistema', title: 'Madrid Startup Bar', desc: 'Comunidad y eventos del ecosistema madrileño.', url: 'https://www.instagram.com/madridstartupbar/' },
    { cat: 'Guías', title: 'Cómo validar una idea en una semana', desc: 'Plantilla que usamos en los talleres de Start.', url: '#' },
    { cat: 'Guías', title: 'Plantilla de pitch de 3 minutos', desc: 'Estructura, timing y errores habituales.', url: '#' },
    { cat: 'Financiación', title: 'ENISA · Jóvenes Emprendedores', desc: 'Préstamos participativos para proyectos de menores de 40 años, sin aval.', url: 'https://www.enisa.es' },
    { cat: 'Ecosistema', title: 'South Summit', desc: 'Uno de los grandes encuentros de startups e inversores de Europa, en Madrid.', url: 'https://www.southsummit.co' },
  ],
};
