export const site = {
  name: 'Start UC3M',
  claim: 'Piensa diferente, actúa con propósito',
  description:
    'Start UC3M es la asociación de emprendedores de la Universidad Carlos III de Madrid: eventos, comunidad y proyectos para pasar de la idea a algo real.',
  email: 'info@startuc3m.org',
  course: '2026/27',
  social: {
    instagram: 'https://www.instagram.com/startuc3m/',
    linkedin: 'https://www.linkedin.com/company/start-uc3m/',
    tiktok: 'https://www.tiktok.com/@startuc3m',
    youtube: 'https://www.youtube.com/@StartUC3MG',
  },
  nav: [
    { label: 'Eventos', href: '/eventos' },
    { label: 'Podcast', href: '/podcast' },
    { label: 'Equipo', href: '/equipo' },
    { label: 'Blog', href: '/blog' },
    { label: 'Patrocina', href: '/patrocina' },
    { label: 'Recursos', href: '/recursos' },
  ],
  sponsors: ['NomuLabs', 'Pitchless', 'Lovable', 'Racks', 'TeamLabs', 'Madrid Startup Bar', 'Opinión20', 'ULVMAND'],
  departments: [
    { name: 'Junta directiva', short: 'Marca el rumbo', desc: 'Marca el rumbo de Start UC3M. Define los objetivos del curso, coordina el trabajo de todos los departamentos y representa a la asociación ante la universidad y el resto del ecosistema emprendedor.' },
    { name: 'Eventos', short: 'Da forma a todo lo que organizamos', desc: 'Da forma a todo lo que la asociación organiza. Diseña el calendario del curso, coordina los espacios, los ponentes y los materiales de cada convocatoria, y se ocupa de que el día del evento todo salga según lo previsto.' },
    { name: 'Comunicación', short: 'Da voz a Start', desc: 'Da voz a Start UC3M. Gestiona las redes sociales, escribe los contenidos que se publican y cubre los eventos con fotografía y vídeo para que quede constancia de lo que se hace.' },
    { name: 'Marketing', short: 'Cómo se ve Start desde fuera', desc: 'Se encarga de cómo se ve Start UC3M desde fuera. Diseña las campañas de cada evento, cuida la identidad visual de la asociación y crea los materiales gráficos que acompañan a todo lo que se publica.' },
    { name: 'RRHH', short: 'Las personas que forman Start', desc: 'Se encarga de las personas que forman Start. Elige a quién entra, acompaña a los nuevos durante sus primeros meses y organiza las formaciones del curso y las actividades internas que mantienen unido al equipo.' },
    { name: 'Partnerships', short: 'Las empresas que apoyan a Start', desc: 'Construye la relación con las empresas que apoyan a Start UC3M. Busca nuevos patrocinadores, negocia las condiciones de cada colaboración y mantiene el contacto con los socios a lo largo del curso.' },
    { name: 'Legal', short: 'El marco jurídico', desc: 'Se ocupa del marco jurídico de la asociación. Revisa los convenios con empresas y patrocinadores, mantiene al día los estatutos y se asegura de que cada actividad cumple con la normativa de la universidad.' },
    { name: 'IT', short: 'Producto y web', desc: 'Construye y mantiene la web, las herramientas internas y todo lo que Start necesita para funcionar en digital.' },
  ],
  team: [
    { name: 'Ioana Nedelcu', role: 'Presidenta', dept: 'Junta directiva', linkedin: 'https://www.linkedin.com/in/ioananedelcu/' },
    { name: 'Ana Giménez', role: 'Vicepresidenta', dept: 'Junta directiva', linkedin: 'http://www.linkedin.com/in/ana-gimenez-de-luis-93a528293' },
    { name: 'Alejandro Ausina', role: 'Responsable', dept: 'IT', linkedin: 'https://www.linkedin.com/in/alejandro-ausina/' },
    { name: 'Lidia Wang', role: 'Responsable', dept: 'Marketing', linkedin: 'http://www.linkedin.com/in/lidia-wang-058433389' },
    { name: 'Irene Ibáñez', role: 'Responsable', dept: 'RRHH', linkedin: 'https://www.linkedin.com/in/ireneibanezcasao/' },
    { name: 'Alicia Gascón', role: 'Responsable', dept: 'Eventos', linkedin: 'https://www.linkedin.com/in/alicia-gasc%C3%B3n-valero-41a828387/' },
    { name: 'Juan Vicente Zerpa', role: 'Asociado', dept: 'IT', linkedin: 'https://www.linkedin.com/in/juan-vicente-zerpa/' },
    { name: 'Uxío López', role: 'Responsable', dept: 'Comunicación', linkedin: 'https://www.linkedin.com/in/uxio-lopez-0b6a09386/' },
    { name: 'María Martín', role: 'Responsable', dept: 'Legal', linkedin: 'https://www.linkedin.com/in/maria-martin-dominguez-9569332a6/' },
    { name: 'Pedro Rodríguez', role: 'Responsable', dept: 'Partnerships', linkedin: 'https://www.linkedin.com/in/pedro-rodr%C3%ADguez-ramos-2bb75a292/' },
    { name: 'María Aguilar', role: 'Asociada', dept: 'RRHH', linkedin: '' },
    { name: 'Gonzalo Torrijos', role: 'Asociado', dept: 'Eventos', linkedin: 'https://www.linkedin.com/in/gonzalo-torrijos/' },
    { name: 'Pablo Juan', role: 'Asociado', dept: 'Legal', linkedin: 'https://www.linkedin.com/in/pablo-juan-conde/' },
  ],
  tiers: [
    { name: 'Partner anual', desc: 'Todo el curso, todos los eventos, marca en web, redes y campus.', perks: ['Logo en todos los eventos del curso', 'Presencia en web, links y newsletter', 'Acceso a la comunidad y a la bolsa de talento', 'Mesa propia en StartXperience y Start Camp'] },
    { name: 'Gold', desc: 'Un evento grande con tu marca y presencia todo el año.', perks: ['Evento con naming ("Buildathon × Tu marca")', 'Logo en web y redes todo el curso', 'Charla o taller propio', 'Acceso a los perfiles de los asistentes'] },
    { name: 'Silver', desc: 'Presencia en un evento concreto.', perks: ['Logo en la cartelería y en la ficha del evento', 'Mención en redes antes y después', 'Stand o espacio el día del evento'] },
    { name: 'Colaborador', desc: 'Producto, espacio, créditos o mentores.', perks: ['Logo en la ficha del evento', 'Agradecimiento en redes'] },
  ],
  links: [
    { label: 'Apuntarme al Buildathon', href: '/eventos/buildathon-pitchless-nomulabs', featured: true },
    { label: 'Quiero entrar en Start', href: '/unete' },
    { label: 'Podcast', href: '/podcast' },
    { label: 'Próximos eventos', href: '/eventos' },
    { label: 'Patrocina Start', href: '/patrocina' },
    { label: 'Blog', href: '/blog' },
  ],
  resources: [
    { cat: 'UC3M', title: 'Vicerrectorado de Emprendimiento UC3M', desc: 'Programas, incubadora y ayudas de la universidad.', url: 'https://www.uc3m.es/emprendimiento/emprende' },
    { cat: 'UC3M', title: 'Asociaciones de estudiantes', desc: 'Cómo funcionan las asociaciones y cómo crear la tuya.', url: 'https://www.uc3m.es/ss/Satellite/AsociacionesEst/es/TextoDosColumnas/1371383720362/' },
    { cat: 'Herramientas', title: 'Lovable', desc: 'Construye un MVP sin código. Lo usamos en el Buildathon.', url: 'https://lovable.dev' },
    { cat: 'Herramientas', title: 'Luma', desc: 'Para publicar y gestionar eventos.', url: 'https://luma.com' },
    { cat: 'Ecosistema', title: 'TeamLabs', desc: 'Laboratorio de aprendizaje radical y espacio de eventos en Madrid.', url: 'https://teamlabs.es' },
    { cat: 'Ecosistema', title: 'Madrid Startup Bar', desc: 'Comunidad y eventos del ecosistema madrileño.', url: 'https://www.instagram.com/madridstartupbar/' },
    { cat: 'Guías', title: 'Cómo validar una idea en una semana', desc: 'Plantilla que usamos en los talleres de Start.', url: '#' },
    { cat: 'Guías', title: 'Plantilla de pitch de 3 minutos', desc: 'Estructura, timing y errores habituales.', url: '#' },
  ],
};
